
	-- 禁言状态
	GAG_STATUS_START = 0	-- 初始化
	GAG_STATUS_OFFLINE = 1	-- GAG_STATUS_OFFLINE		= 1		//玩家离线
	GAG_STATUS_END = 1	-- 已禁言
	-- 设置GM表的状态
	GIFT_PACKS_STATUS_START		= 0	--初始
	GIFT_PACKS_STATUS_SENDING	= 1	--发放中
	GIFT_PACKS_STATUS_OK		= 2	--已发放
	GIFT_PACKS_STATUS_END		= 3	--已结束
	--踢人
	KICKING_STATUS_START		=0		--初始化
	KICKING_STATUS_END			=1		--已踢
	--设置GM表的状态
	GM_LEVEL_TABLE_START = 0	-- 初始化
	GM_LEVEL_TABLE_END = 1	-- 已执行
	-- 封号的状态类型
	LOCKING_STATUS_START = 0	-- 初始化
	LOCKING_STATUS_RUNNING = 1	-- 封号中
	LOCKING_STATUS_END = 2	-- 结束
	-- 封号的状态类型
	LOCKING_STATUS_START = 0	-- 初始化
	LOCKING_STATUS_RUNNING = 1	-- 封号中
	LOCKING_STATUS_END = 2	-- 结束
	-- 公告的状态类型
	SYSTEM_NOTICE_STATUS_START = 0	-- 初始状态
	SYSTEM_NOTICE_STATUS_RUNNING = 1	-- 运行中
	SYSTEM_NOTICE_STATUS_END = 2	-- 结束
	SYSTEM_NOTICE_STATUS_DELETE = 3	-- 将删除
	SYSTEM_NOTICE_STATUS_GARBAGE = 4	-- 已删除	
	-- 充值状态		
	RECHARGE_STATUS_TYPE_START		= 0		--初始化
	RECHARGE_STATUS_TYPE_RUNMING	= 1		--订单推送中
	RECHARGE_STATUS_TYPE_END		= 2		--结束	
	RECHARGE_STATUS_TYPE_ERROR		= 3		--订单出错
	RECHARGE_STATUS_TYPE_OUTLINE	= 4		--订单离线中
	RECHARGE_STATUS_TYPE_POSTURL_INVALID = 5--推送订单地址失效（应用服注册失败）
	RECHARGE_STATUS_TYPE_GIVEUP		= 6		--订单作废
	-- 公告的状态类型
	SYSTEM_NOTICE_STATUS_START = 0	-- 初始状态
	SYSTEM_NOTICE_STATUS_RUNNING = 1	-- 运行中
	SYSTEM_NOTICE_STATUS_END = 2	-- 结束
	SYSTEM_NOTICE_STATUS_DELETE = 3	-- 将删除
	SYSTEM_NOTICE_STATUS_GARBAGE = 4	-- 已删除
    --订单状态
    ORDER_STATUS_NEW = 0 --新的订单
    ORDER_STATUS_OVER = 1 --已经处理
    ORDER_STATUS_TIME_OUT = 2 --已经过期
